name: example-landofile-changed-alert
recipe: lamp

services:
  appserver:
    build:
      # Save a hash of our lando config for future integrity checking
      - sha1sum /app/.lando.yml > ~/.lando.yml.sha1

events:
  post-start:
    # Alert user if landofile and current environment are out of sync.
    - cd /app && sha1sum --status -c ~/.lando.yml.sha1 || echo $(echo $(tput setab 1 && tput setaf 7)Your Lando environment is outdated! Please run \"lando rebuild\" to update.$(tput sgr 0))
